{"name": "test03_mis_audit", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <scripts.test02_mis.TestMis object at 0x000002089EE5BE80>\n\n    def test03_mis_audit(self):\n        # 1.调用审核文章方法\n        r = self.mis.api_mis_audit()\n        try:\n            # 2.断言\n>           Tool.common_assert(r)\n\nscripts\\test02_mis.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'tool.tool.Tool'>, response = <Response [403]>, status_code = 201\n\n    @classmethod\n    def common_assert(cls, response, status_code=201):\n        log.info(\"正在调用公共断言方法！\")\n        # 断言状态码\n>       assert status_code == response.status_code\nE       AssertionError\n\ntool\\tool.py:21: AssertionError"}, "attachments": [{"name": "log", "source": "e1f197f5-211b-4845-8bd2-9a603e65adc1-attachment.txt", "type": "text/plain"}], "start": 1628854328730, "stop": 1628854328800, "uuid": "9e37ec3e-f6a9-4e48-904e-841cb724157a", "historyId": "b465eea778f8ece01716f4527f84b689", "testCaseId": "90ff882230c9f80dbc7a2baf9bff7e41", "fullName": "scripts.test02_mis.TestMis#test03_mis_audit", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test02_mis"}, {"name": "subSuite", "value": "TestMis"}, {"name": "host", "value": "DESKTOP-3AQ9FK9"}, {"name": "thread", "value": "3696-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test02_mis"}]}